### ISSUE TITLE
CSV Data Set Config

### ISSUE THREAD

**Issue by thimoonxy** [winebarrel/qrn#13]
Hi, 
is it possible to provide configs so that qrn randomly chooses different args rather than running fix sqls ?

e.g.  preparing a set of username/password , qrn picks the pairs randomly,  to mimic concurrently login actions.

Refer to : https://jmeter.apache.org/usermanual/component_reference.html#CSV_Data_Set_Config

Thx, Simon

**Comment by winebarrel** [comment]
Sorry.
At the moment qrn is not going to support such a feature.

[super-smack](https://github.com/winebarrel/super-smack) may solve the problem.
